---
services:
    tor-socks-proxy:
        container_name: tor-socks-proxy
        build: .
        image: tor-socks-proxy:local
        ports:
            - "8853:53/udp"
            - "9150:9150/tcp"
            - "3128:3128/tcp"
        restart: unless-stopped
